### PR TITLE
Use default options when netlify.toml isn't available

### LINKED ISSUE #8: Bug: plugin fails with an error when there is no [nimbella] setting in netlify.toml
To reproduce:
Use https://github.com/nimbella/netlify-plugin-nimbella#minimal-netlify-toml-configuration, e.g. a `netlify.toml` as such:
```toml
[[plugins]]
package = "netlify-plugin-nimbella"
```

See https://app.netlify.com/sites/determined-johnson-c85a62/deploys/5f79bdc630173a00089717dc

Error message:
```
Error: Cannot read property 'functions' of undefined
```

I believe this error is coming from:
https://github.com/nimbella/netlify-plugin-nimbella/blob/108706af452c6f0c9b8675113ea5446756bc4fd6/index.js#L96

I would also recommend checking if `netlify.toml` exists as some sites don't have it (e.g. you install the plugin using the UI)

### PR DESCRIPTION
**Pull request by satyarohith**
Tested. Everything is working as expected. 

Closes #8

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -133,8 +146,8 @@ module.exports = {
           run: utils.run,
           functionsDir: functionsBuildDir,
           secretsPath: join(process.cwd(), 'env.json'),
-          timeout: config.nimbella.timeout || 6000, // Default is 10 seconds
-          memory: config.nimbella.memory || 256 // Default is 256MB (max for free tier)
+          timeout: options.timeout, // Default is 10 seconds
```
Comment (rabbah) [inline index.js]: Comment says 10 seconds, but value in the default options is 6s. 
```suggestion
          timeout: options.timeout, // Default is 6 seconds
```

**Review by rabbah — APPROVED** [review]
